import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function OnBoardingLayout({
    children,
    setup,
}: Readonly<{
    children: React.ReactNode;
    setup: React.ReactNode;
}>) {
    return (
        <>
            {children}
            {setup}
        </>
    );
}
